[tool.semantic_release]
branch = "master"
version_toml = ["blender_manifest.toml:version"]
changelog_file = "CHANGELOG.md"
upload_to_pypi = false
upload_to_release = true
build_command = "zip -r ortho_scale_219_{version}.zip __init__.py blender_manifest.toml LICENSE.md README.md"