from __future__ import annotations
from typing import Any,Callable,Literal,Set
from .types import*
from .props import*
from . import utils
context:Context
data:BlendData
path_resolve:Callable[...,Any]
class ObjectOps:
 def select_all(self,action:Literal['SELECT','DESELECT','TOGGLE','INVERT']='SELECT')->Set[Literal['RUNNING_MODAL','CANCELLED','FINISHED','PASS_THROUGH']]:...
 def delete(self,use_global:bool=False)->Set[Literal['RUNNING_MODAL','CANCELLED','FINISHED','PASS_THROUGH']]:...
class MeshOps:
 def primitive_cube_add(self,location:tuple[float,float,float]=(0.0,0.0,0.0))->Set[Literal['RUNNING_MODAL','CANCELLED','FINISHED','PASS_THROUGH']]:...
class OrthoScale219Ops:
 def add_config(self)->Set[Literal['RUNNING_MODAL','CANCELLED','FINISHED','PASS_THROUGH']]:...
 def remove_config(self)->Set[Literal['RUNNING_MODAL','CANCELLED','FINISHED','PASS_THROUGH']]:...
 def add_blender_object(self)->Set[Literal['RUNNING_MODAL','CANCELLED','FINISHED','PASS_THROUGH']]:...
 def add_selected_objects(self)->Set[Literal['RUNNING_MODAL','CANCELLED','FINISHED','PASS_THROUGH']]:...
 def remove_object(self)->Set[Literal['RUNNING_MODAL','CANCELLED','FINISHED','PASS_THROUGH']]:...
class RenderOps:
 def ortho_scale_219_compile(self)->Set[Literal['RUNNING_MODAL','CANCELLED','FINISHED','PASS_THROUGH']]:...
class Ops:
 object:ObjectOps
 mesh:MeshOps
 ortho_scale_219:OrthoScale219Ops
 render:RenderOps
ops:Ops