from typing import Callable,Optional,TypeVar,Union
F=TypeVar('F')
class ApproxBase:...
def approx(expected:Union[float,int],rel:Optional[float]=None,abs:Optional[float]=None,nan_ok:bool=False)->ApproxBase:...
def fixture(scope:str='function',autouse:bool=False)->Callable[[F],F]:...