name: Python Tests with Pytest
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-blender
      - name: Download Blender
        run: |
          wget -q https://download.blender.org/release/Blender4.3/blender-4.3.0-linux-x64.tar.xz
          tar -xf blender-4.3.0-linux-x64.tar.xz
          mv blender-4.3.0-linux-x64 blender
      - name: Run Pytest
        run: cd tests && pytest --blender-executable ../blender/blender